VALIDATE_ALL_CODEBASE: true
DISABLE_LINTERS: COPYPASTE_JSCPD

REPOSITORY_GITLEAKS_PR_COMMITS_SCAN: true
ACTION_ACTIONLINT_ARGUMENTS: -shellcheck=
JSON_V8R_FILTER_REGEX_EXCLUDE: tasks.json
SPELL_CSPELL_CONFIG_FILE: .linters/cspell.json
