on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

name: Test
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  lint:
    name: Run Golang-CI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Run Golang-CI Lint
        uses: golangci/golangci-lint-action@v8

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Test
        run: >
          go tool gotestsum
          --jsonfile gotestsum.json
          --packages="./..."
          --format testname
          --
          -coverpkg=./...
          -coverprofile=coverage.out

      - name: Convert report into ctrf
        if: ${{ !cancelled() }}
        run: go tool go-ctrf-json-reporter -output report.json < gotestsum.json

      - name: Publish Test Report to PR
        uses: ctrf-io/github-test-reporter@v1.0.21
        if: ${{ !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Test Results
          report-path: "report.json"
          pull-request: true
          pull-request-report: true
          comment-tag: ${{ github.workflow }}-${{ github.job }}
          overwrite-comment: true

      - name: Publish Test Report to Summary
        uses: ctrf-io/github-test-reporter@v1.0.21
        if: ${{ !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Test Results
          report-path: "report.json"
          summary: true
          summary-report: true
          failed-report: true

      - name: Update coverage report
        uses: ncruces/go-coverage-report@main
        with:
          coverage-file: coverage.out
          report: "true"
          chart: "true"
          amend: "true"

  megalinter:
    name: Run Megalinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: MegaLinter
        id: ml
        uses: oxsecurity/megalinter/flavors/go@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_STATUS_REPORTER: true
